name = "Achedmy"
uuid = "3809e951-761c-4e21-b9ed-bc66e666ef58"
authors = ["Moshir Harsh <btemoshir@gmail.com>"]
version = "0.1.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Einsum = "b7d42ee7-0b51-5a75-98ca-779d3107e4c0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
KadanoffBaym = "82532805-809c-4ef0-842b-4b00c5e9be5f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
KadanoffBaym = "1.3"
julia = "1.9.4"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
MomentClosure = "01a1b25a-ecf0-48c5-ae58-55bfd5393600"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
